//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testrepit
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public string admin { get; set; }
        public string id { get; set; }
        public Nullable<bool> isAdmin { get; set; }
    }
}
